version: "3.9"
services:

  slave2:
    image: redis:6.2.1 
    container_name: slave2
    hostname: slave2
    expose: 
      - 6379
    restart: always
    
    volumes:
      - redis-data:/data:rw
      - ${PWD}/redis-slaves-conf:/etc/redis
    # environment:
    # - ALLOW_EMPTY_PASSWORD=yes
   
    networks:
        redis:
          aliases:
            - slave2

  sentinel3:
    image: redis:sentinel 
    hostname: sentinel3
    container_name: sentinel3
    depends_on:
      - slave2
    restart: always
    networks:
        redis:
          aliases:
            - sentinel3
volumes:
  redis-data:
networks:
  redis:
    external: true 