version: "3.9"
services:

  slave1:
    image: redis:6.2.1 
    container_name: slave1
    hostname: slave1
    expose: 
      - 6379
    restart: always
    volumes:
      - redis-data:/data:rw
      - ${PWD}/redis-slaves-conf:/etc/redis
    # environment:
    # - ALLOW_EMPTY_PASSWORD=yes
   
    networks:
        redis:
          aliases:
            - slave1

  sentinel2:
    image: redis:sentinel 
    hostname: sentinel2
    container_name: sentinel2
    depends_on:
      - slave1
    restart: always
    networks:
        redis:
          aliases:
            - sentinel2
  
volumes:
  redis-data:
networks:
  redis:
    external: true 